# IS590OM Final Project

The Jupyter notebook is Ke-Rou Wang's IS590OM Final Project.

## UFO dataset

For this dataset, I firstly remove tuples that have null values where the column name states, and then change the DATE format from %m/%d/%Y to Y only. For selecting columns, I only remain columns State and time at this point but will remain more for my final delivery.   
Remain columns: 'State', 'Time', 'City', 'Form', 'Event Time(sec)', 'Description', 'X coordinate', 'Y coordinate'.

In [1]:
import os, csv, sys, json, operator, codecs, re
from datetime import datetime
import pandas as pd
import requests
import io
import bqplot
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def read_csv_input(input_file):
    res = []
    with codecs.open(os.path.join(input_file), 'r', 'ISO-8859-1') as f:
        #(x.replace('\0', '') for x in f)
        reader = csv.DictReader(f)

        for row in reader:
            if row['State'] != None and row['State'] != '' and row['Isglobal'] == 'us': #remove null value
                #res_dict = {}
                #dt = datetime.strptime(row['Time'], '%m/%d/%Y %H:%M')
                #res_dict['UFO Year'] = dt.year # reset format of UFO.year
                #res_dict['State'] = row['State']
                #res.append(res_dict)
                res.append(dict(row))

    return res

In [3]:
def WriteDictToCSV(csv_file,csv_columns,dict_data):
    with open(csv_file, 'w') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
        writer.writeheader()
        for data in dict_data:
            writer.writerow(data)
    return

In [4]:
input_file = os.path.join('.', 'ufo-scrubbed-geocoded-time-standardized-00.csv')
dictu = read_csv_input(input_file)
# outputput_file = os.path.join('.', 'IS590OM_combined_data.csv')
# WriteDictToCSV(outputput_file, ['UFO Year','State'], dictu)

## Population dataset

Read the dataset population and see if I should alter anything. Even though there are some values remain as 0, but they will not change the consequence. In addition, there are no columns that are needed to be abandoned, so this dataset is mainly for direct combination.  
Remain columns: All columns will be remain.

In [5]:
dfp = pd.read_excel('Resident Population by State, Annual.xlsx')
dfp

,States,1949,1950,1951,1952,1953,1954,1955,1956,1957,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Alabama,3000,3058,3059,3068,3053,3014,3050,3071,3109,...,4530.729,4569.805,4628.981,4672.840,4718.206,4757.938,4785.448,4798.834,4815.564,4830.460
1,Alaska,0,135,158,189,205,215,222,224,231,...,659.286,666.946,675.302,680.300,687.455,698.895,713.906,722.038,730.399,737.045
2,Arizona,714,756,785,842,894,933,987,1053,1125,...,5652.404,5839.077,6029.141,6167.681,6280.362,6343.154,6407.774,6473.497,6556.629,6634.999
3,Arkansas,1844,1908,1901,1838,1780,1734,1725,1704,1733,...,2749.686,2781.097,2821.761,2848.650,2874.554,2896.843,2921.978,2940.407,2952.109,2959.549
4,California,10337,10677,11134,11635,12251,12746,13133,13713,14264,...,35574.576,35827.943,36021.202,36250.311,36604.337,36961.229,37320.903,37641.823,37960.782,38280.824
5,Colorado,1295,1325,1326,1365,1431,1493,1546,1625,1664,...,4575.013,4631.888,4720.423,4803.868,4889.730,4972.195,5048.281,5121.771,5193.721,5270.482
6,Connecticut,2032,2016,2028,2081,2168,2249,2300,2316,2359,...,3496.094,3506.956,3517.460,3527.270,3545.579,3561.807,3579.125,3588.023,3594.395,3594.915
7,Delaware,316,321,331,341,351,368,389,408,426,...,830.803,845.150,859.268,871.749,883.874,891.730,899.595,907.316,915.188,923.638
8,Florida,2668,2810,2980,3157,3310,3505,3747,4047,4372,...,17415.318,17842.038,18166.990,18367.842,18527.305,18652.644,18845.785,19093.352,19326.230,19563.166
9,Georgia,3325,3458,3531,3584,3558,3602,3636,3701,3766,...,8769.252,8925.922,9155.813,9349.988,9504.843,9620.846,9711.810,9801.578,9901.496,9973.326
10,Hawaii,0,498,514,517,510,505,539,559,584,...,1273.569,1292.729,1309.731,1315.675,1332.213,1346.717,1363.963,1379.252,1394.905,1408.453
11,Idaho,570,590,589,587,596,600,618,628,642,...,1391.802,1428.241,1468.669,1505.105,1534.320,1554.439,1570.773,1583.828,1595.441,1611.530
12,Illinois,8670,8738,8790,8956,9065,9252,9435,9530,9668,...,12589.773,12609.903,12643.955,12695.866,12747.038,12796.778,12840.762,12867.291,12884.119,12898.269
13,Indiana,3958,3967,4096,4148,4182,4264,4363,4458,4529,...,6233.007,6278.616,6332.669,6379.599,6424.806,6459.325,6490.436,6516.045,6537.640,6568.367
14,Iowa,2578,2625,2617,2626,2629,2626,2679,2703,2716,...,2953.635,2964.454,2982.644,2999.212,3016.734,3032.870,3050.767,3066.054,3076.097,3093.078
15,Kansas,1925,1916,1950,1977,1994,2042,2093,2119,2128,...,2734.373,2745.299,2762.931,2783.785,2808.076,2832.704,2858.213,2869.035,2885.361,2893.510
16,Kentucky,2849,2936,2941,2920,2903,2902,2910,2898,2928,...,4146.101,4182.742,4219.239,4256.672,4289.878,4317.074,4348.200,4369.488,4386.381,4404.817
17,Louisiana,2634,2697,2769,2842,2866,2883,2946,3032,3115,...,4552.238,4576.628,4302.665,4375.581,4435.586,4491.648,4544.532,4575.184,4600.814,4624.577
18,Maine,903,917,916,915,913,927,934,938,943,...,1313.688,1318.787,1323.619,1327.040,1330.509,1329.590,1327.632,1328.150,1327.691,1328.196
19,Maryland,2329,2355,2441,2500,2567,2685,2742,2811,2873,...,5546.935,5592.379,5627.367,5653.408,5684.965,5730.388,5788.642,5838.991,5887.072,5923.704
20,Massachusetts,4741,4686,4654,4650,4806,4910,4882,4891,4929,...,6412.281,6403.290,6410.084,6431.559,6468.967,6517.613,6566.431,6613.149,6663.158,6713.944
21,Michigan,6332,6407,6497,6650,6822,7066,7285,7467,7569,...,10055.315,10051.137,10036.081,10001.284,9946.889,9901.591,9877.535,9881.521,9896.930,9913.349
22,Minnesota,2935,2997,3010,3030,3050,3113,3172,3240,3274,...,5087.713,5119.598,5163.555,5207.203,5247.018,5281.203,5310.843,5345.668,5376.550,5413.693
23,Mississippi,2085,2176,2163,2152,2105,2064,2060,3240,2088,...,2889.010,2905.943,2904.978,2928.350,2947.806,2958.774,2970.536,2978.470,2983.767,2988.797
24,Missouri,3882,3964,4015,3972,4020,4066,4134,4163,4189,...,5747.741,5790.300,5842.704,5887.612,5923.916,5961.088,5995.976,6009.641,6024.081,6040.658
25,Montana,569,593,596,602,616,624,636,656,667,...,930.009,940.102,952.692,964.706,976.415,983.982,990.722,997.221,1003.754,1013.564
26,Nebraska,1302,1327,1316,1311,1318,1340,1374,1397,1394,...,1749.370,1761.497,1772.693,1783.440,1796.378,1812.683,1829.536,1840.538,1853.323,1865.414
27,Nevada,157,162,168,181,195,213,237,250,260,...,2346.222,2432.143,2522.658,2601.072,2653.630,2684.665,2702.464,2712.799,2744.566,2776.972
28,New Hampshire,533,532,529,535,547,554,557,566,572,...,1290.121,1298.492,1308.389,1312.540,1315.906,1316.102,1316.777,1319.815,1323.962,1326.408
29,New Jersey,4889,4872,5006,5125,5229,5360,5502,5615,5737,...,8634.561,8651.974,8661.679,8677.885,8711.090,8755.602,8799.624,8827.783,8845.483,8858.362
30,New Mexico,644,689,717,735,756,763,785,806,847,...,1903.808,1932.274,1962.137,1990.070,2010.662,2036.802,2064.588,2080.395,2087.549,2092.792
31,New York,14892,14865,14890,15192,15527,15814,15966,16112,16374,...,19171.567,19132.610,19104.631,19132.335,19212.436,19307.066,19400.080,19498.514,19574.549,19628.043
32,North Carolina,3911,4068,4120,4109,4120,4131,4242,4309,4368,...,8553.152,8705.407,8917.270,9118.037,9309.449,9449.566,9574.293,9656.754,9749.123,9843.599
33,North Dakota,597,619,604,608,609,611,615,613,612,...,644.705,646.089,649.422,652.822,657.569,664.968,674.710,685.136,701.116,721.999
34,Ohio,7973,7980,8061,8275,8591,8873,9017,9207,9410,...,11452.251,11463.320,11481.213,11500.468,11515.391,11528.896,11539.327,11543.463,11548.369,11576.576
35,Oklahoma,2105,2229,2210,2219,2182,2209,2250,2273,2282,...,3525.233,3548.597,3594.090,3634.349,3668.976,3717.572,3759.632,3787.821,3818.600,3853.205
36,Oregon,1431,1532,1556,1582,1601,1626,1659,1698,1712,...,3569.463,3613.202,3670.883,3722.417,3768.748,3808.600,3837.532,3871.728,3899.118,3922.908
37,Pennsylvania,10390,10507,10461,10503,10662,10817,10939,10972,10954,...,12410.722,12449.990,12510.809,12563.937,12612.285,12666.858,12711.158,12744.583,12766.827,12776.621
38,Rhode Island,801,786,784,802,815,816,823,840,851,...,1074.579,1067.916,1063.096,1057.315,1055.003,1053.646,1053.938,1053.536,1054.601,1055.122
39,South Carolina,2029,2113,2167,2178,2181,2176,2200,2229,2274,...,4210.921,4270.150,4357.847,4444.110,4528.996,4589.872,4635.656,4671.422,4717.112,4764.153
40,South Dakota,631,655,655,651,648,655,663,670,666,...,770.396,775.493,783.033,791.623,799.124,807.067,816.165,823.484,833.496,842.270
41,Tennessee,3236,3315,3372,3352,3319,3359,3415,3415,3434,...,5910.809,5991.057,6088.766,6175.727,6247.411,6306.019,6355.301,6397.410,6451.281,6493.432
42,Texas,7623,7776,8111,8314,8336,8382,8660,8830,9070,...,22394.023,22778.123,23359.580,23831.983,24309.039,24801.761,25242.679,25646.227,26089.620,26489.464
43,Utah,671,696,706,724,739,750,783,809,826,...,2401.580,2457.719,2525.507,2597.746,2663.029,2723.421,2775.334,2814.216,2853.467,2897.927
44,Vermont,369,379,378,375,379,377,375,377,376,...,619.920,621.215,622.892,623.481,624.151,624.817,625.880,626.979,626.063,626.212
45,Virginia,3292,3315,3434,3504,3557,3555,3588,3722,3844,...,7475.575,7577.105,7673.725,7751.000,7833.496,7925.937,8023.680,8100.469,8185.229,8253.053
46,Washington,2294,2387,2424,2448,2466,2516,2604,2668,2724,...,6178.645,6257.305,6370.753,6461.587,6562.231,6667.426,6742.902,6821.655,6892.876,6962.906
47,West Virginia,1930,2006,1984,1957,1929,1905,1880,1857,1843,...,1816.438,1820.492,1827.912,1834.052,1840.310,1847.775,1854.214,1856.074,1856.764,1853.873
48,Wisconsin,3391,3438,3439,3469,3506,3608,3679,3742,3791,...,5514.026,5546.166,5577.655,5610.775,5640.996,5669.264,5690.479,5704.755,5719.855,5736.952
49,Wyoming,277,290,291,293,290,293,307,312,314,...,509.106,514.157,522.667,534.876,546.043,559.851,564.483,567.224,576.270,582.123

## Climate dataset

Similar to the previous 2 datasets, read the file and then decide and then decide which column is needed to remain.  
Remain columns: 'States','States Abbr.','Record Dates','Temperature Value', 'Temperature Rank', 'Temperature Departure from mean','Precipitation Value', 'Precipitation Rank', 'Precipitation Departure from mean'.

In [6]:
dfc = pd.read_excel('NOAA National Centers for Environmental information(IS590OM).xlsx')
dfc

,States,States Abbr.,Record Dates,Temperature Value,Temperature Rank,Temperature Departure from mean,Precipitation Value,Precipitation Rank,Precipitation Departure from mean
0,Alabama,AL,194901 - 194912,64.2°F,61,1.1°F,"57.36""",39,"1.78"""
1,Alabama,AL,195001 - 195012,63.1°F,43,0.0°F,"53.04""",26,"-2.54"""
2,Alabama,AL,195101 - 195112,63.8°F,54,0.7°F,"52.92""",25,"-2.66"""
3,Alabama,AL,195201 - 195212,63.3°F,46,0.2°F,"46.70""",6,"-8.88"""
4,Alabama,AL,195301 - 195312,63.8°F,54,0.7°F,"59.45""",46,"3.87"""
...,...,...,...,...,...,...,...,...,...
3244,Hawaii,HI,200901 - 200912,--,--,--,--,--,--
3245,Hawaii,HI,201001 - 201012,78.4°F,43,0.7°F,78.4°F,43,0.7°F
3246,Hawaii,HI,201101 - 201112,78.5°F,49,0.8°F,78.5°F,49,0.8°F
3247,Hawaii,HI,201201 - 201212,78.1°F,36,0.4°F,78.1°F,36,0.4°F
3248,Hawaii,HI,201301 - 201312,78.4°F,43,0.7°F,78.4°F,43,0.7°F

In [7]:
dfc['Record Dates'] = dfc['Record Dates'].str.slice(0,4)
dfct = dfc[['States','States Abbr.','Record Dates','Temperature Value', 'Temperature Rank', 'Temperature Departure from mean','Precipitation Value', 'Precipitation Rank', 'Precipitation Departure from mean']]
dictres = dfct.to_dict('records')

## Combine data

Now we have several columns remain:  
UFO => {'State', 'Time', 'City', 'Form', 'Event Time(sec)', 'Description', 'X coordinate', 'Y coordinate'}
Population => {'State', 'Year from 1949 to 2013'}  
Climate => {'States','States Abbr.','Record Dates','Temperature Value', 'Temperature Rank', 'Temperature Departure from mean','Precipitation Value', 'Precipitation Rank', 'Precipitation Departure from mean'}

However, there are still a few things that is needed to be done. For dataset Population, since all tuples' values in population are /k based, I will have to make all year.population values*1000.

In [8]:
dictp = dfp.to_dict('records')
for data in dictres:
    for dp in dictp:
        if dp['States'].lower() == data['States'].lower():
            data['Population'] = int(dp[int(data['Record Dates'])]*1000) #all pp values*1000

In addition, for dataset UFO, I would like to delete a few columns include {'Isglobal', 'Event Time',  and 'Record Time'}.

In [9]:
for du in dictu:
    dt = datetime.strptime(du['Time'], '%m/%d/%Y %H:%M')
    du_year = dt.year
    for data in dictres:
        if du['State'].lower() == data['States Abbr.'].lower() and du_year == int(data['Record Dates']):
            du['State Abbr.'] = data['States Abbr.']
            du['State'] = data['States']
            du['Temperature Value'] = data['Temperature Value']
            du['Temperature Rank'] = data['Temperature Rank']
            du['Temperature Departure from mean'] = data['Temperature Departure from mean']
            du['Precipitation Value'] = data['Precipitation Value']
            du['Precipitation Rank'] = data['Precipitation Rank']
            du['Precipitation Departure from mean'] = data['Precipitation Departure from mean']
            du['Population'] = data['Population']
            del du['Isglobal']
            del du['Event Time']
            del du['Record Time']

In [10]:
#for data in dictres:
#    data['ufo'] = 1
#    for du in dictu:
#        if du['State'].lower() == data['States Abbr.'].lower() and du['UFO Year'] == int(data['Record Dates']):
#            data['ufo'] = data['ufo'] + 1 # count total_num of ufo events/year
#            
#dictres

Final step: output a .xlsx file rather than csv since csv's row limit is too restrict for my output.

In [11]:
#outputput_file = os.path.join('.', 'IS590OM_combined_data.csv')
#WriteDictToCSV(outputput_file, dictres[0].keys(), dictres)
#outputput_file = os.path.join('.', 'IS590OM_combined_data_new.csv')
#WriteDictToCSV(outputput_file, dictu[0].keys(), dictu)

In [12]:
df = pd.DataFrame(dictu)
#df

df.to_excel('IS590OM_combined_data_new.xlsx')

## Reference

1. UFO dataset: https://data.world/timothyrenner/ufo-sightings/file/nuforc_reports.json
2. Population dataset: https://fred.stlouisfed.org/release/tables?rid=118&eid=259194&od=1900-01-01#
3. Climate dataset: https://www.ncdc.noaa.gov/cag/city/time-series/USW00022521/tavg/12/12/1949-2013?base_prd=true&begbaseyear=1948&endbaseyear=2000